In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

In [2]:
df = pd.read_csv("Weather_Data.csv")
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

# Data Preprocessing

### One Hot Encoding

In [3]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

In [4]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

# Training Data and Test Data

In [5]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [6]:
df_sydney_processed = df_sydney_processed.astype(float)

In [7]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

In [8]:
df.describe()

MinTemp      MaxTemp     Rainfall  Evaporation     Sunshine  \
count  3271.000000  3271.000000  3271.000000  3271.000000  3271.000000   
mean     14.877102    23.005564     3.342158     5.175787     7.168970   
std       4.554710     4.483752     9.917746     2.757684     3.815966   
min       4.300000    11.700000     0.000000     0.000000     0.000000   
25%      11.000000    19.600000     0.000000     3.200000     4.250000   
50%      14.900000    22.800000     0.000000     4.800000     8.300000   
75%      18.800000    26.000000     1.400000     7.000000    10.200000   
max      27.600000    45.800000   119.400000    18.400000    13.600000   

       WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
count    3271.000000   3271.000000   3271.000000  3271.000000  3271.000000   
mean       41.476307     15.077041     19.294405    68.243962    54.698563   
std        10.806951      7.043825      7.453331    15.086127    16.279241   
min        17.000000      0.000000      0.000000    19.000000    10.000000   
25%        35.000000     11.000000     15.000000    58.000000    44.000000   
50%        41.000000     15.000000     19.000000    69.000000    56.000000   
75%        44.000000     20.000000     24.000000    80.000000    64.000000   
max        96.000000     54.000000     57.000000   100.000000    99.000000   

       Pressure9am  Pressure3pm     Cloud9am     Cloud3pm      Temp9am  \
count  3271.000000  3271.000000  3271.000000  3271.000000  3271.000000   
mean   1018.334424  1016.003085     4.318557     4.176093    17.821461   
std       7.020090     7.019915     2.526923     2.411274     4.894316   
min     986.700000   989.800000     0.000000     0.000000     6.400000   
25%    1013.700000  1011.300000     2.000000     2.000000    13.800000   
50%    1018.600000  1016.300000     5.000000     4.000000    18.200000   
75%    1023.100000  1020.800000     7.000000     7.000000    21.700000   
max    1039.000000  1036.700000     9.000000     8.000000    36.500000   

           Temp3pm  
count  3271.000000  
mean     21.543656  
std       4.297053  
min      10.200000  
25%      18.400000  
50%      21.300000  
75%      24.500000  
max      44.700000

# Linear Regression

#### Q1) Use the train_test_split function to split the features and Y dataframes with a test_size of 0.2 and the random_state set to 10.

In [9]:
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size = 0.2, random_state = 10)
print('Train set: ',x_train.shape, y_train.shape)
print('Test set: ',x_test.shape, y_test.shape)

Train set:  (2616, 66) (2616,)
Test set:  (655, 66) (655,)


#### Q2) Create and train a Linear Regression model called LinearReg using the training data (x_train, y_train).

In [10]:
from sklearn import linear_model
Linear_regr = linear_model.LinearRegression()
Linear_regr.fit(x_train, y_train)

LinearRegression()

#### Q3) Now use the predict method on the testing data (x_test) and save it to the array predictions.

In [11]:
predictions = Linear_regr.predict(x_test)
print(predictions[0:5])

[0.1317997  0.27613258 0.97812843 0.28744316 0.13240433]


#### Q4) Using the predictions and the y_test dataframe calculate the value for each metric using the appropriate function.

In [12]:
from sklearn.metrics import r2_score
LinearRegression_MAE = np.mean(np.absolute(predictions - y_test))
print("Mean absolute error: %.2f", LinearRegression_MAE)
LinearRegression_MSE = np.mean((predictions - y_test) ** 2)
print("Mean Squared Error (MSE) : %.2f" % LinearRegression_MSE)
LinearRegression_R2 = r2_score(y_test , predictions)
print("R2-score: %.2f" % LinearRegression_R2)

Mean absolute error: %.2f 0.25632199585892773
Mean Squared Error (MSE) : 0.12
R2-score: 0.43


#### Q5) Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.

In [13]:
from tabulate import tabulate

dict = [["LinearRegression_MAE",LinearRegression_MAE],["LinearRegression_MSE",LinearRegression_MSE],
       ["LinearRegression_R2",LinearRegression_R2]]
Report = pd.DataFrame(dict)
print(tabulate(Report))

-  --------------------  --------
0  LinearRegression_MAE  0.256322
1  LinearRegression_MSE  0.115722
2  LinearRegression_R2   0.427125
-  --------------------  --------


# KNN

### Normalize Data

In [14]:
x_train_norm = preprocessing.StandardScaler().fit(x_train).transform(x_train.astype(float))
x_train_norm[0:1]

array([[-0.01652033, -0.22351516,  3.05624855, -0.3528601 , -1.49917863,
         0.81280282,  0.54686322,  0.63906113,  1.45139438, -0.34685075,
         1.42955371,  1.46816932,  1.45395941,  1.16411721, -0.42868452,
         0.06119933, -1.73381821,  1.73381821, -0.19412228, -0.26363085,
        -0.20951051, -0.09209294, -0.23052136, -0.22306777, -0.12773808,
        -0.151901  , -0.2296003 , -0.14380157,  3.64624217, -0.23417666,
        -0.12773808, -0.88431688, -0.1596252 , -0.20347303, -0.21540659,
        -0.15708867, -0.21050268, -0.18101787, -0.15836152, -0.16702646,
        -0.18325819, -0.1694292 , -0.21540659, -0.17646286, -0.19412228,
        -0.2413554 , -0.13816088,  1.26506823, -0.41667788, -0.17061927,
        -0.48850421, -0.35035237,  2.94769213, -0.13525922, -0.33219954,
        -0.14654687, -0.1077076 , -0.13671719, -0.28615705, -0.26196842,
        -0.28927244, -0.21830526, -0.11475228, -0.25777751, -0.24312407,
        -0.18436945]])

#### Q6) Create and train a KNN model called KNN using the training data (x_train, y_train) with the n_neighbors parameter set to 4.

In [15]:
KNN = KNeighborsClassifier(n_neighbors = 4).fit(x_train_norm, y_train)
KNN

KNeighborsClassifier(n_neighbors=4)

In [16]:
x_test_norm = preprocessing.StandardScaler().fit(x_test).transform(x_test.astype(float))
x_test_norm[0:2]

array([[ 0.84642333,  2.78130101, -0.38229187,  0.28968134,  0.72582356,
         1.30802878, -0.25231332, -0.34734376, -1.65628147, -1.83288088,
        -1.42072048, -1.16518113, -0.54363274,  0.34123298,  1.62475832,
         2.11826429,  0.65346404, -0.65346404, -0.20734905, -0.26835255,
        -0.21908902, -0.11119694, -0.24468459, -0.19920477, -0.12451456,
        -0.11803342, -0.24816996, -0.15309311, -0.30575995,  4.82278543,
        -0.11119694, -0.85603985, -0.14778658, -0.21908902, -0.19920477,
        -0.15823755, -0.19076794, -0.16323531, -0.15823755, -0.16809954,
        -0.16809954, -0.13661083, -0.25503069, -0.18199733, -0.20331122,
        -0.25840906, -0.10393493, -0.79587465,  2.38404561, -0.19076794,
        -0.47360222, -0.34591635,  3.12052959, -0.11803342, -0.33755826,
        -0.10393493, -0.11119694, -0.13069333, -0.27803351, -0.27483388,
        -0.35142445, -0.21908902, -0.10393493, -0.24816996, -0.24468459,
        -0.19920477],
       [ 0.02576925,  0.38749

#### Q7) Now use the predict method on the testing data (x_test) and save it to the array predictions.

In [17]:
predictions = KNN.predict(x_test)
predictions[0:5]

C:\Users\ashut\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


array([0., 0., 0., 0., 0.])

#### Q8) Using the predictions and the y_test dataframe calculate the value for each metric using the appropriate function.

In [36]:
from sklearn import metrics

KNN_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
print("KNN_Accuracy_Score: " % KNN_Accuracy_Score)
KNN_JaccardIndex = metrics.jaccard_score(y_test, predictions,pos_label=0.0)
print("KNN_JaccardIndex: %.4f" % KNN_JaccardIndex)
KNN_F1_Score = metrics.f1_score(y_test, predictions, average='weighted')
print("KNN_F1_Score: %.4f" % KNN_F1_Score)

KNN_Accuracy_Score: 
KNN_JaccardIndex: 0.7221
KNN_F1_Score: 0.6056


# Decision Tree

#### Q9) Create and train a Decision Tree model called Tree using the training data (x_train, y_train).

In [19]:
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size = 0.2, random_state = 10)
print('Train set: ',x_train.shape, y_train.shape)
print('Test set: ',x_test.shape, y_test.shape)

Train set:  (2616, 66) (2616,)
Test set:  (655, 66) (655,)


In [20]:
Tree = DecisionTreeClassifier(criterion="entropy", max_depth=4)
Tree

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [21]:
Tree.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

#### Q10) Now use the predict method on the testing data (x_test) and save it to the array predictions.

In [22]:
predictions = Tree.predict(x_test)

In [23]:
print(predictions [0:5])
print(y_test [0:5])

[0. 0. 1. 0. 0.]
3066    0.0
2456    0.0
1629    1.0
838     1.0
2506    0.0
Name: RainTomorrow, dtype: float64


#### Q11) Using the predictions and the y_test dataframe calculate the value for each metric using the appropriate function.

In [24]:
from sklearn import metrics
import matplotlib.pyplot as plt

Tree_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
print("Tree_Accuracy_Score: " % Tree_Accuracy_Score)
Tree_JaccardIndex = jaccard_score(y_test, predictions,pos_label=0.0)
print("Tree_JaccardIndex: %.4f" % Tree_JaccardIndex)
Tree_F1_Score = f1_score(y_test, predictions, average='weighted')
print("Tree_F1_Score: %.4f" % Tree_F1_Score)

Tree_Accuracy_Score: 
Tree_JaccardIndex: 0.7817
Tree_F1_Score: 0.8133


# Logistic Regression

#### Q12) Use the train_test_split function to split the features and Y dataframes with a test_size of 0.2 and the random_state set to 1.

In [25]:
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size = 0.2, random_state = 1)
print('Train set: ',x_train.shape, y_train.shape)
print('Test set: ',x_test.shape, y_test.shape)

Train set:  (2616, 66) (2616,)
Test set:  (655, 66) (655,)


#### Q13) Create and train a LogisticRegression model called LR using the training data (x_train, y_train) with the solver parameter set to liblinear.

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C = 0.01, solver='liblinear').fit(x_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

#### Q14) Now, use the predict and predict_proba methods on the testing data (x_test) and save it as 2 arrays predictions and predict_proba.

In [27]:
predictions = LR.predict(x_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

In [28]:
predict_proba = LR.predict_proba(x_test)
predict_proba[0:5]

array([[0.71865806, 0.28134194],
       [0.97588275, 0.02411725],
       [0.49701229, 0.50298771],
       [0.66413194, 0.33586806],
       [0.97404704, 0.02595296]])

#### Q15) Using the predictions, predict_proba and the y_test dataframe calculate the value for each metric using the appropriate function.

In [29]:
from sklearn.metrics import log_loss
log_loss(y_test, predict_proba)

LR_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
print("LR_Accuracy_Score: " % LR_Accuracy_Score)
LR_JaccardIndex = jaccard_score(y_test, predictions,pos_label=0.0)
print("LR_JaccardIndex: %.4f" % LR_JaccardIndex)
LR_F1_Score = f1_score(y_test, predictions, average='weighted')
print("LR_F1_Score: %.4f" % LR_F1_Score)
LR_Log_Loss = log_loss(y_test, predict_proba)
print ("LR_Log_Loss: : %.2f" % LR_Log_Loss)

LR_Accuracy_Score: 
LR_JaccardIndex: 0.7942
LR_F1_Score: 0.8205
LR_Log_Loss: : 0.38


# SVM

#### Q16) Create and train a SVM model called SVM using the training data (x_train, y_train).

In [30]:
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size = 0.2, random_state = 1)
print('Train set: ',x_train.shape, y_train.shape)
print('Test set: ',x_test.shape, y_test.shape)

Train set:  (2616, 66) (2616,)
Test set:  (655, 66) (655,)


In [31]:
from sklearn import svm
SVM = svm.SVC(kernel='rbf')
SVM.fit(x_train, y_train)

SVC()

#### Q17) Now use the predict method on the testing data (x_test) and save it to the array predictions.

In [32]:
predictions = SVM.predict(x_test)
predictions[0:5]

array([0., 0., 0., 0., 0.])

#### Q18) Using the predictions and the y_test dataframe calculate the value for each metric using the appropriate function.

In [33]:
SVM_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
print("SVM_Accuracy_Score: ", SVM_Accuracy_Score)
SVM_JaccardIndex = jaccard_score(y_test, predictions,pos_label=0.0)
print("SVM_JaccardIndex: %.4f" % SVM_JaccardIndex)
SVM_F1_Score = f1_score(y_test, predictions, average='weighted')
print("SVM_F1_Score: %.4f" % SVM_F1_Score)

SVM_Accuracy_Score:  0.7221374045801526
SVM_JaccardIndex: 0.7221
SVM_F1_Score: 0.6056


# Report

#### Q19) Show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.

In [34]:
from tabulate import tabulate
dict1 = {'LinearRegression' : [LinearRegression_MAE,LinearRegression_MSE,LinearRegression_R2],
         'KNN' : [KNN_Accuracy_Score,KNN_JaccardIndex,KNN_F1_Score],
         'DecisionTree' : [Tree_Accuracy_Score,Tree_JaccardIndex,Tree_F1_Score],
         'LogisticRegression' : [LR_Accuracy_Score,LR_JaccardIndex,LR_F1_Score],
         'SVM' : [SVM_Accuracy_Score,SVM_JaccardIndex,SVM_F1_Score]
        }
dict2 = [["LinearRegression_MAE",LinearRegression_MAE],["LinearRegression_MSE",LinearRegression_MSE],
         ["LinearRegression_R2",LinearRegression_R2],
         ["KNN_Accuracy_Score",KNN_Accuracy_Score],["KNN_JaccardIndex",KNN_JaccardIndex],
         ["KNN_F1_Score",KNN_F1_Score],
         ["Tree_Accuracy_Score",Tree_Accuracy_Score],["Tree_JaccardIndex",Tree_JaccardIndex],
         ["Tree_F1_Score",Tree_F1_Score],
         ["LR_Accuracy_Score",LR_Accuracy_Score],["LR_JaccardIndex",LR_JaccardIndex],
         ["LR_F1_Score",LR_F1_Score],["LR_log_Loss",LR_Log_Loss],
         ["SVM_Accuracy_Score",SVM_Accuracy_Score],["SVM_JaccardIndex",SVM_JaccardIndex],
         ["SVM_F1_Score",SVM_F1_Score]]
Report = pd.DataFrame(data=dict2)
print(tabulate(Report))

--  --------------------  --------
 0  LinearRegression_MAE  0.256322
 1  LinearRegression_MSE  0.115722
 2  LinearRegression_R2   0.427125
 3  KNN_Accuracy_Score    0.719084
 4  KNN_JaccardIndex      0.719084
 5  KNN_F1_Score          0.601578
 6  Tree_Accuracy_Score   0.818321
 7  Tree_JaccardIndex     0.781651
 8  Tree_F1_Score         0.813263
 9  LR_Accuracy_Score     0.827481
10  LR_JaccardIndex       0.794171
11  LR_F1_Score           0.820545
12  LR_log_Loss           0.380085
13  SVM_Accuracy_Score    0.722137
14  SVM_JaccardIndex      0.722137
15  SVM_F1_Score          0.605622
--  --------------------  --------
